//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnightsAndDragonsCalculator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KnightsAndDragonsCalculator.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor data missing.
        /// </summary>
        internal static string ArmorDataMissing {
            get {
                return ResourceManager.GetString("ArmorDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor not found.
        /// </summary>
        internal static string ArmorNotFound {
            get {
                return ResourceManager.GetString("ArmorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Air Armor.
        /// </summary>
        internal static string CommonAirArmor {
            get {
                return ResourceManager.GetString("CommonAirArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Earth Armor.
        /// </summary>
        internal static string CommonEarthArmor {
            get {
                return ResourceManager.GetString("CommonEarthArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Fire Armor.
        /// </summary>
        internal static string CommonFireArmor {
            get {
                return ResourceManager.GetString("CommonFireArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Spirit Armor.
        /// </summary>
        internal static string CommonSpiritArmor {
            get {
                return ResourceManager.GetString("CommonSpiritArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Water Armor.
        /// </summary>
        internal static string CommonWaterArmor {
            get {
                return ResourceManager.GetString("CommonWaterArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level data missing.
        /// </summary>
        internal static string LevelDataMissing {
            get {
                return ResourceManager.GetString("LevelDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snakeskin Armor.
        /// </summary>
        internal static string SnakeskinArmor {
            get {
                return ResourceManager.GetString("SnakeskinArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wing Warrior&apos;s Armor.
        /// </summary>
        internal static string UncommonAirArmor {
            get {
                return ResourceManager.GetString("UncommonAirArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stonescale Plate Armor.
        /// </summary>
        internal static string UncommonEarthArmor {
            get {
                return ResourceManager.GetString("UncommonEarthArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragonflame Armor.
        /// </summary>
        internal static string UncommonFireArmor {
            get {
                return ResourceManager.GetString("UncommonFireArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystic Armor.
        /// </summary>
        internal static string UncommonSpiritArmor {
            get {
                return ResourceManager.GetString("UncommonSpiritArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seafoam Armor.
        /// </summary>
        internal static string UncommonWaterArmor {
            get {
                return ResourceManager.GetString("UncommonWaterArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wicker Mantle.
        /// </summary>
        internal static string WickerMantle {
            get {
                return ResourceManager.GetString("WickerMantle", resourceCulture);
            }
        }
    }
}
