//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnightsAndDragonsCalculatorApplication.Calculator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KnightsAndDragonsCalculatorApplication.Calculator.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abominable Platemail.
        /// </summary>
        internal static string AbominablePlatemail {
            get {
                return ResourceManager.GetString("AbominablePlatemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admiral&apos;s Battleworn Regalia.
        /// </summary>
        internal static string AdmiralsBattlewornRegalia {
            get {
                return ResourceManager.GetString("AdmiralsBattlewornRegalia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admiral&apos;s Nemesis Uniform.
        /// </summary>
        internal static string AdmiralsNemesisUniform {
            get {
                return ResourceManager.GetString("AdmiralsNemesisUniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aegis of Sky Majesty.
        /// </summary>
        internal static string AegisOfSkyMajesty {
            get {
                return ResourceManager.GetString("AegisOfSkyMajesty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aegis Of The Dragon.
        /// </summary>
        internal static string AegisOfTheDragon {
            get {
                return ResourceManager.GetString("AegisOfTheDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aegis Of The Fallen.
        /// </summary>
        internal static string AegisOfTheFallen {
            get {
                return ResourceManager.GetString("AegisOfTheFallen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aegis Of The Wyvern.
        /// </summary>
        internal static string AegisOfTheWyvern {
            get {
                return ResourceManager.GetString("AegisOfTheWyvern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Fusion Boost Armor.
        /// </summary>
        internal static string AirFusionBoostArmor {
            get {
                return ResourceManager.GetString("AirFusionBoostArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arborsteel Vanguard.
        /// </summary>
        internal static string ArborsteelVanguard {
            get {
                return ResourceManager.GetString("ArborsteelVanguard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Of Boreas.
        /// </summary>
        internal static string ArmorOfBoreas {
            get {
                return ResourceManager.GetString("ArmorOfBoreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Of Eurus.
        /// </summary>
        internal static string ArmorOfEurus {
            get {
                return ResourceManager.GetString("ArmorOfEurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Of Notus.
        /// </summary>
        internal static string ArmorOfNotus {
            get {
                return ResourceManager.GetString("ArmorOfNotus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Of Phyrus.
        /// </summary>
        internal static string ArmorOfPhyrus {
            get {
                return ResourceManager.GetString("ArmorOfPhyrus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Of The Bear.
        /// </summary>
        internal static string ArmorOfTheBear {
            get {
                return ResourceManager.GetString("ArmorOfTheBear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor of the Devoted.
        /// </summary>
        internal static string ArmorOfTheDevoted {
            get {
                return ResourceManager.GetString("ArmorOfTheDevoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor of the Infernal Lord.
        /// </summary>
        internal static string ArmorOfTheInfernalLord {
            get {
                return ResourceManager.GetString("ArmorOfTheInfernalLord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Of The Wolf.
        /// </summary>
        internal static string ArmorOfTheWolf {
            get {
                return ResourceManager.GetString("ArmorOfTheWolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asherah&apos;s Armor.
        /// </summary>
        internal static string AsherahsArmor {
            get {
                return ResourceManager.GetString("AsherahsArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asherah&apos;s Nemesis.
        /// </summary>
        internal static string AsherahsNemesis {
            get {
                return ResourceManager.GetString("AsherahsNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassin&apos;s Shroud.
        /// </summary>
        internal static string AssassinsShroud {
            get {
                return ResourceManager.GetString("AssassinsShroud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asura Armor.
        /// </summary>
        internal static string AsuraArmor {
            get {
                return ResourceManager.GetString("AsuraArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlantean Avenger Armor.
        /// </summary>
        internal static string AtlanteanAvengerArmor {
            get {
                return ResourceManager.GetString("AtlanteanAvengerArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banshee&apos;s Nemesis Wrappings.
        /// </summary>
        internal static string BansheesNemesisWrappings {
            get {
                return ResourceManager.GetString("BansheesNemesisWrappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbarian Raiding Gear.
        /// </summary>
        internal static string BarbarianRaidingGear {
            get {
                return ResourceManager.GetString("BarbarianRaidingGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battlesuit Remnants.
        /// </summary>
        internal static string BattlesuitRemnants {
            get {
                return ResourceManager.GetString("BattlesuitRemnants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battlesuit&apos;s Nemesis Garb.
        /// </summary>
        internal static string BattlesuitsNemesisGarb {
            get {
                return ResourceManager.GetString("BattlesuitsNemesisGarb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beastmaster Battlegear.
        /// </summary>
        internal static string BeastmasterBattlegear {
            get {
                return ResourceManager.GetString("BeastmasterBattlegear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behemoth&apos;s Nemesis.
        /// </summary>
        internal static string BehemothsNemesis {
            get {
                return ResourceManager.GetString("BehemothsNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behemoth&apos;s Vanguard.
        /// </summary>
        internal static string BehemothsVanguard {
            get {
                return ResourceManager.GetString("BehemothsVanguard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beringar&apos;s Nemesis.
        /// </summary>
        internal static string BeringarsNemesis {
            get {
                return ResourceManager.GetString("BeringarsNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackfrost Raiment.
        /// </summary>
        internal static string BlackfrostRaiment {
            get {
                return ResourceManager.GetString("BlackfrostRaiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Kaleidoscopic Raiment.
        /// </summary>
        internal static string BlackKaleidoscopicRaiment {
            get {
                return ResourceManager.GetString("BlackKaleidoscopicRaiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazeborne Vanguard.
        /// </summary>
        internal static string BlazeborneVanguard {
            get {
                return ResourceManager.GetString("BlazeborneVanguard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazestone Mantle.
        /// </summary>
        internal static string BlazestoneMantle {
            get {
                return ResourceManager.GetString("BlazestoneMantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boilerplate Armor.
        /// </summary>
        internal static string BoilerplateArmor {
            get {
                return ResourceManager.GetString("BoilerplateArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bone Harvester&apos;s Garb.
        /// </summary>
        internal static string BoneHarvestersGarb {
            get {
                return ResourceManager.GetString("BoneHarvestersGarb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boreas&apos;s Nemesis.
        /// </summary>
        internal static string BoreassNemesis {
            get {
                return ResourceManager.GetString("BoreassNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brawler&apos;s Armor.
        /// </summary>
        internal static string BrawlersArmor {
            get {
                return ResourceManager.GetString("BrawlersArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chimera Corps Uniform.
        /// </summary>
        internal static string ChimeraCorpsUniform {
            get {
                return ResourceManager.GetString("ChimeraCorpsUniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chitinous Armor.
        /// </summary>
        internal static string ChitinousArmor {
            get {
                return ResourceManager.GetString("ChitinousArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circe&apos;s Nemesis.
        /// </summary>
        internal static string CircesNemesis {
            get {
                return ResourceManager.GetString("CircesNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clayplate Mantle.
        /// </summary>
        internal static string ClayplateMantle {
            get {
                return ResourceManager.GetString("ClayplateMantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud King&apos;s Finery.
        /// </summary>
        internal static string CloudKingsFinery {
            get {
                return ResourceManager.GetString("CloudKingsFinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudrange Platemail.
        /// </summary>
        internal static string CloudrangePlatemail {
            get {
                return ResourceManager.GetString("CloudrangePlatemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combustion Armor.
        /// </summary>
        internal static string CombustionArmor {
            get {
                return ResourceManager.GetString("CombustionArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Air Armor.
        /// </summary>
        internal static string CommonAirArmor {
            get {
                return ResourceManager.GetString("CommonAirArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Earth Armor.
        /// </summary>
        internal static string CommonEarthArmor {
            get {
                return ResourceManager.GetString("CommonEarthArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Fire Armor.
        /// </summary>
        internal static string CommonFireArmor {
            get {
                return ResourceManager.GetString("CommonFireArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Spirit Armor.
        /// </summary>
        internal static string CommonSpiritArmor {
            get {
                return ResourceManager.GetString("CommonSpiritArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Water Armor.
        /// </summary>
        internal static string CommonWaterArmor {
            get {
                return ResourceManager.GetString("CommonWaterArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corvus&apos;s Nemesis.
        /// </summary>
        internal static string CorvussNemesis {
            get {
                return ResourceManager.GetString("CorvussNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crab&apos;s Nemesis Uniform.
        /// </summary>
        internal static string CrabsNemesisUniform {
            get {
                return ResourceManager.GetString("CrabsNemesisUniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crius Armor.
        /// </summary>
        internal static string CriusArmor {
            get {
                return ResourceManager.GetString("CriusArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Prince&apos;s Royal Armor.
        /// </summary>
        internal static string DarkPrincesRoyalArmor {
            get {
                return ResourceManager.GetString("DarkPrincesRoyalArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Dragon Mail.
        /// </summary>
        internal static string DeepDragonMail {
            get {
                return ResourceManager.GetString("DeepDragonMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Dragon&apos;s Nemesis Armor.
        /// </summary>
        internal static string DeepDragonsNemesisArmor {
            get {
                return ResourceManager.GetString("DeepDragonsNemesisArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deva&apos;s Nemesis.
        /// </summary>
        internal static string DevasNemesis {
            get {
                return ResourceManager.GetString("DevasNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dorar&apos;s Nemesis.
        /// </summary>
        internal static string DorarsNemesis {
            get {
                return ResourceManager.GetString("DorarsNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon Tamer Costume.
        /// </summary>
        internal static string DragonTamerCostume {
            get {
                return ResourceManager.GetString("DragonTamerCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth Fusion Boost Armor.
        /// </summary>
        internal static string EarthFusionBoostArmor {
            get {
                return ResourceManager.GetString("EarthFusionBoostArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eldritch Keeper&apos;s Robes.
        /// </summary>
        internal static string EldritchKeepersRobes {
            get {
                return ResourceManager.GetString("EldritchKeepersRobes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        internal static string ElementAir {
            get {
                return ResourceManager.GetString("ElementAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ElementAll {
            get {
                return ResourceManager.GetString("ElementAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        internal static string ElementEarth {
            get {
                return ResourceManager.GetString("ElementEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        internal static string ElementFire {
            get {
                return ResourceManager.GetString("ElementFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirit.
        /// </summary>
        internal static string ElementSpirit {
            get {
                return ResourceManager.GetString("ElementSpirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string ElementWater {
            get {
                return ResourceManager.GetString("ElementWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ember Lizard&apos;s Nemesis.
        /// </summary>
        internal static string EmberLizardsNemesis {
            get {
                return ResourceManager.GetString("EmberLizardsNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embersteel Armor.
        /// </summary>
        internal static string EmbersteelArmor {
            get {
                return ResourceManager.GetString("EmbersteelArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor data missing..
        /// </summary>
        internal static string ErrorArmorDataMissing {
            get {
                return ResourceManager.GetString("ErrorArmorDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor not found..
        /// </summary>
        internal static string ErrorArmorNotFound {
            get {
                return ResourceManager.GetString("ErrorArmorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armors with same element cannot be combined..
        /// </summary>
        internal static string ErrorArmorSameElement {
            get {
                return ResourceManager.GetString("ErrorArmorSameElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Stats data not available for this armor..
        /// </summary>
        internal static string ErrorArmorStatsNotAvailable {
            get {
                return ResourceManager.GetString("ErrorArmorStatsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss data must be provided..
        /// </summary>
        internal static string ErrorBossDataNotProvided {
            get {
                return ResourceManager.GetString("ErrorBossDataNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild data must be provided..
        /// </summary>
        internal static string ErrorGuildDataNotProvided {
            get {
                return ResourceManager.GetString("ErrorGuildDataNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armorsmith count must be greater than 0..
        /// </summary>
        internal static string ErrorInvalidArmorsmithCount {
            get {
                return ResourceManager.GetString("ErrorInvalidArmorsmithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armorsmith level must be between 1 and 3..
        /// </summary>
        internal static string ErrorInvalidArmorsmithLevel {
            get {
                return ResourceManager.GetString("ErrorInvalidArmorsmithLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss level must be between 1 and 60..
        /// </summary>
        internal static string ErrorInvalidBossLevel {
            get {
                return ResourceManager.GetString("ErrorInvalidBossLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss stats must be greater than 0..
        /// </summary>
        internal static string ErrorInvalidBossStats {
            get {
                return ResourceManager.GetString("ErrorInvalidBossStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Cannot be flagged as Nemesis as it is not a Nemesis armor..
        /// </summary>
        internal static string ErrorInvalidIsNemesis {
            get {
                return ResourceManager.GetString("ErrorInvalidIsNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Level must be between 1 and {1}..
        /// </summary>
        internal static string ErrorInvalidPlayerArmorLevel {
            get {
                return ResourceManager.GetString("ErrorInvalidPlayerArmorLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of knights must be between 1 and 5..
        /// </summary>
        internal static string ErrorInvalidPlayerKnightCount {
            get {
                return ResourceManager.GetString("ErrorInvalidPlayerKnightCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player level must be between 1 and 100..
        /// </summary>
        internal static string ErrorInvalidPlayerLevel {
            get {
                return ResourceManager.GetString("ErrorInvalidPlayerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start level must be between 1 and target level..
        /// </summary>
        internal static string ErrorInvalidStartLevel {
            get {
                return ResourceManager.GetString("ErrorInvalidStartLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target level must be between 1 and target armor&apos;s maximum level..
        /// </summary>
        internal static string ErrorInvalidTargetLevel {
            get {
                return ResourceManager.GetString("ErrorInvalidTargetLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level data missing..
        /// </summary>
        internal static string ErrorLevelDataMissing {
            get {
                return ResourceManager.GetString("ErrorLevelDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet..
        /// </summary>
        internal static string ErrorNotImplementYet {
            get {
                return ResourceManager.GetString("ErrorNotImplementYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Armor not found..
        /// </summary>
        internal static string ErrorPlayerArmorNotFound {
            get {
                return ResourceManager.GetString("ErrorPlayerArmorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 armor must be provided..
        /// </summary>
        internal static string ErrorPlayerArmorsDataNotProvided {
            get {
                return ResourceManager.GetString("ErrorPlayerArmorsDataNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player data must be provided..
        /// </summary>
        internal static string ErrorPlayerDataNotProvided {
            get {
                return ResourceManager.GetString("ErrorPlayerDataNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethereal Garment.
        /// </summary>
        internal static string EtherealGarment {
            get {
                return ResourceManager.GetString("EtherealGarment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eurus&apos;s Nemesis.
        /// </summary>
        internal static string EurussNemesis {
            get {
                return ResourceManager.GetString("EurussNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exorcist&apos;s Vestments.
        /// </summary>
        internal static string ExorcistsVestments {
            get {
                return ResourceManager.GetString("ExorcistsVestments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faerie Dragons&apos; Nemesis Armor.
        /// </summary>
        internal static string FaerieDragonsNemesisArmor {
            get {
                return ResourceManager.GetString("FaerieDragonsNemesisArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featherblade Battlegear.
        /// </summary>
        internal static string FeatherbladeBattlegear {
            get {
                return ResourceManager.GetString("FeatherbladeBattlegear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenris&apos;s Nemesis.
        /// </summary>
        internal static string FenrissNemesis {
            get {
                return ResourceManager.GetString("FenrissNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Data/armors.xml.
        /// </summary>
        internal static string FileNameArmors {
            get {
                return ResourceManager.GetString("FileNameArmors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Data/levels.xml.
        /// </summary>
        internal static string FileNameLevels {
            get {
                return ResourceManager.GetString("FileNameLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Data/logs.xml.
        /// </summary>
        internal static string FileNameLogs {
            get {
                return ResourceManager.GetString("FileNameLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Eater&apos;s Nemesis.
        /// </summary>
        internal static string FireEatersNemesis {
            get {
                return ResourceManager.GetString("FireEatersNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Fusion Boost Armor.
        /// </summary>
        internal static string FireFusionBoostArmor {
            get {
                return ResourceManager.GetString("FireFusionBoostArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flamegem Nemesis Armor.
        /// </summary>
        internal static string FlamegemNemesisArmor {
            get {
                return ResourceManager.GetString("FlamegemNemesisArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flamehunter&apos;s Garb.
        /// </summary>
        internal static string FlamehuntersGarb {
            get {
                return ResourceManager.GetString("FlamehuntersGarb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flamestorm Finery.
        /// </summary>
        internal static string FlamestormFinery {
            get {
                return ResourceManager.GetString("FlamestormFinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flame Summoner&apos;s Shroud.
        /// </summary>
        internal static string FlameSummonersShroud {
            get {
                return ResourceManager.GetString("FlameSummonersShroud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowstone Battlegear.
        /// </summary>
        internal static string FlowstoneBattlegear {
            get {
                return ResourceManager.GetString("FlowstoneBattlegear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgemaster&apos;s Garb.
        /// </summary>
        internal static string ForgemastersGarb {
            get {
                return ResourceManager.GetString("ForgemastersGarb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgemaster&apos;s Nemesis Armor.
        /// </summary>
        internal static string ForgemastersNemesisArmor {
            get {
                return ResourceManager.GetString("ForgemastersNemesisArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgestone Aegis.
        /// </summary>
        internal static string ForgestoneAegis {
            get {
                return ResourceManager.GetString("ForgestoneAegis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glacier Armor.
        /// </summary>
        internal static string GlacierArmor {
            get {
                return ResourceManager.GetString("GlacierArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glorg&apos;s Nemesis.
        /// </summary>
        internal static string GlorgsNemesis {
            get {
                return ResourceManager.GetString("GlorgsNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorlog&apos;s Nemesis Armor.
        /// </summary>
        internal static string GorlogsNemesisArmor {
            get {
                return ResourceManager.GetString("GorlogsNemesisArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian&apos;s Battlegear.
        /// </summary>
        internal static string GuardiansBattlegear {
            get {
                return ResourceManager.GetString("GuardiansBattlegear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champion.
        /// </summary>
        internal static string GuildRankChampion {
            get {
                return ResourceManager.GetString("GuildRankChampion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander.
        /// </summary>
        internal static string GuildRankCommander {
            get {
                return ResourceManager.GetString("GuildRankCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Commander.
        /// </summary>
        internal static string GuildRankHighCommander {
            get {
                return ResourceManager.GetString("GuildRankHighCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        internal static string GuildRankMaster {
            get {
                return ResourceManager.GetString("GuildRankMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinel.
        /// </summary>
        internal static string GuildRankSentinel {
            get {
                return ResourceManager.GetString("GuildRankSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-Dragons&apos; Nemesis Costume.
        /// </summary>
        internal static string HalfDragonsNemesisCostume {
            get {
                return ResourceManager.GetString("HalfDragonsNemesisCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-Dragon Warrior&apos;s Armor.
        /// </summary>
        internal static string HalfDragonWarriorsArmor {
            get {
                return ResourceManager.GetString("HalfDragonWarriorsArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horrible Wurm Costume.
        /// </summary>
        internal static string HorribleWurmCostume {
            get {
                return ResourceManager.GetString("HorribleWurmCostume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horseman&apos;s Battlegear.
        /// </summary>
        internal static string HorsemansBattlegear {
            get {
                return ResourceManager.GetString("HorsemansBattlegear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horseman&apos;s Nemesis.
        /// </summary>
        internal static string HorsemansNemesis {
            get {
                return ResourceManager.GetString("HorsemansNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter&apos;s Garb.
        /// </summary>
        internal static string HuntersGarb {
            get {
                return ResourceManager.GetString("HuntersGarb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huntress&apos;s Nemesis Armor.
        /// </summary>
        internal static string HuntresssNemesisArmor {
            get {
                return ResourceManager.GetString("HuntresssNemesisArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydra Hunter&apos;s Mail.
        /// </summary>
        internal static string HydraHuntersMail {
            get {
                return ResourceManager.GetString("HydraHuntersMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydromancer&apos;s Mantle.
        /// </summary>
        internal static string HydromancersMantle {
            get {
                return ResourceManager.GetString("HydromancersMantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydromancer&apos;s Nemesis Finery.
        /// </summary>
        internal static string HydromancersNemesisFinery {
            get {
                return ResourceManager.GetString("HydromancersNemesisFinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Lich&apos;s Nemesis.
        /// </summary>
        internal static string IceLichsNemesis {
            get {
                return ResourceManager.GetString("IceLichsNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackalope&apos;s Chaingarb.
        /// </summary>
        internal static string JackalopesChaingarb {
            get {
                return ResourceManager.GetString("JackalopesChaingarb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackalope&apos;s Nemesis.
        /// </summary>
        internal static string JackalopesNemesis {
            get {
                return ResourceManager.GetString("JackalopesNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jian&apos;s Battlegear.
        /// </summary>
        internal static string JiansBattlegear {
            get {
                return ResourceManager.GetString("JiansBattlegear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jian&apos;s Nemesis Mail.
        /// </summary>
        internal static string JiansNemesisMail {
            get {
                return ResourceManager.GetString("JiansNemesisMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaleidoscopic Starmetal Raiment.
        /// </summary>
        internal static string KaleidoscopicStarmetalRaiment {
            get {
                return ResourceManager.GetString("KaleidoscopicStarmetalRaiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerstman&apos;s Shroud.
        /// </summary>
        internal static string KerstmansShroud {
            get {
                return ResourceManager.GetString("KerstmansShroud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leviathan&apos;s Nemesis.
        /// </summary>
        internal static string LeviathansNemesis {
            get {
                return ResourceManager.GetString("LeviathansNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leviathan&apos;s Platemail.
        /// </summary>
        internal static string LeviathansPlatemail {
            get {
                return ResourceManager.GetString("LeviathansPlatemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning Lord Armor.
        /// </summary>
        internal static string LightningLordArmor {
            get {
                return ResourceManager.GetString("LightningLordArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Flame Armor.
        /// </summary>
        internal static string LivingFlameArmor {
            get {
                return ResourceManager.GetString("LivingFlameArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Fix.
        /// </summary>
        internal static string LogTypeBugFix {
            get {
                return ResourceManager.GetString("LogTypeBugFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string LogTypeData {
            get {
                return ResourceManager.GetString("LogTypeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Feature.
        /// </summary>
        internal static string LogTypeNewFeature {
            get {
                return ResourceManager.GetString("LogTypeNewFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maelstrom Irons.
        /// </summary>
        internal static string MaelstromIrons {
            get {
                return ResourceManager.GetString("MaelstromIrons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantle Of The Beast.
        /// </summary>
        internal static string MantleOfTheBeast {
            get {
                return ResourceManager.GetString("MantleOfTheBeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molten Shroud.
        /// </summary>
        internal static string MoltenShroud {
            get {
                return ResourceManager.GetString("MoltenShroud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monk&apos;s Vestments.
        /// </summary>
        internal static string MonksVestments {
            get {
                return ResourceManager.GetString("MonksVestments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monstrous Garb.
        /// </summary>
        internal static string MonstrousGarb {
            get {
                return ResourceManager.GetString("MonstrousGarb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moontide Platemail.
        /// </summary>
        internal static string MoontidePlatemail {
            get {
                return ResourceManager.GetString("MoontidePlatemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountainvine Shroud.
        /// </summary>
        internal static string MountainvineShroud {
            get {
                return ResourceManager.GetString("MountainvineShroud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nerezza&apos;s Nemesis.
        /// </summary>
        internal static string NerezzasNemesis {
            get {
                return ResourceManager.GetString("NerezzasNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimboss Nemesis Armor.
        /// </summary>
        internal static string NimbossNemesisArmor {
            get {
                return ResourceManager.GetString("NimbossNemesisArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoImage.
        /// </summary>
        internal static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northerner&apos;s Battlegear.
        /// </summary>
        internal static string NorthernersBattlegear {
            get {
                return ResourceManager.GetString("NorthernersBattlegear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notus&apos;s Nemesis.
        /// </summary>
        internal static string NotussNemesis {
            get {
                return ResourceManager.GetString("NotussNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phyrus&apos;s Nemesis.
        /// </summary>
        internal static string PhyrussNemesis {
            get {
                return ResourceManager.GetString("PhyrussNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyromancer&apos;s Mantle.
        /// </summary>
        internal static string PyromancersMantle {
            get {
                return ResourceManager.GetString("PyromancersMantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rageborne Raiment.
        /// </summary>
        internal static string RageborneRaiment {
            get {
                return ResourceManager.GetString("RageborneRaiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raider&apos;s Nemesis Armor.
        /// </summary>
        internal static string RaidersNemesisArmor {
            get {
                return ResourceManager.GetString("RaidersNemesisArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string RarityCommon {
            get {
                return ResourceManager.GetString("RarityCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epic.
        /// </summary>
        internal static string RarityEpic {
            get {
                return ResourceManager.GetString("RarityEpic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion Boost.
        /// </summary>
        internal static string RarityFusionBoost {
            get {
                return ResourceManager.GetString("RarityFusionBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary.
        /// </summary>
        internal static string RarityLegendary {
            get {
                return ResourceManager.GetString("RarityLegendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemesis.
        /// </summary>
        internal static string RarityNemesis {
            get {
                return ResourceManager.GetString("RarityNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        internal static string RarityRare {
            get {
                return ResourceManager.GetString("RarityRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Rare.
        /// </summary>
        internal static string RaritySuperRare {
            get {
                return ResourceManager.GetString("RaritySuperRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra Rare.
        /// </summary>
        internal static string RarityUltraRare {
            get {
                return ResourceManager.GetString("RarityUltraRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        internal static string RarityUncommon {
            get {
                return ResourceManager.GetString("RarityUncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ravenlord&apos;s Mantle.
        /// </summary>
        internal static string RavenlordsMantle {
            get {
                return ResourceManager.GetString("RavenlordsMantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ravenlord&apos;s Nemesis.
        /// </summary>
        internal static string RavenlordsNemesis {
            get {
                return ResourceManager.GetString("RavenlordsNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Kaleidoscopic Armor.
        /// </summary>
        internal static string RedKaleidoscopicArmor {
            get {
                return ResourceManager.GetString("RedKaleidoscopicArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riverstone Mantle.
        /// </summary>
        internal static string RiverstoneMantle {
            get {
                return ResourceManager.GetString("RiverstoneMantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocfeather Robes.
        /// </summary>
        internal static string RocfeatherRobes {
            get {
                return ResourceManager.GetString("RocfeatherRobes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royal Flame Armor.
        /// </summary>
        internal static string RoyalFlameArmor {
            get {
                return ResourceManager.GetString("RoyalFlameArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruby Plate Mail.
        /// </summary>
        internal static string RubyPlateMail {
            get {
                return ResourceManager.GetString("RubyPlateMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sasquatch&apos;s Nemesis.
        /// </summary>
        internal static string SasquatchsNemesis {
            get {
                return ResourceManager.GetString("SasquatchsNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorchstone Aegis.
        /// </summary>
        internal static string ScorchstoneAegis {
            get {
                return ResourceManager.GetString("ScorchstoneAegis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siren&apos;s Nemesis Armor.
        /// </summary>
        internal static string SirensNemesisArmor {
            get {
                return ResourceManager.GetString("SirensNemesisArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky Guardian.
        /// </summary>
        internal static string SkyGuardian {
            get {
                return ResourceManager.GetString("SkyGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slimebane Battlegear.
        /// </summary>
        internal static string SlimebaneBattlegear {
            get {
                return ResourceManager.GetString("SlimebaneBattlegear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snakeskin Armor.
        /// </summary>
        internal static string SnakeskinArmor {
            get {
                return ResourceManager.GetString("SnakeskinArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snowman&apos;s Nemesis.
        /// </summary>
        internal static string SnowmansNemesis {
            get {
                return ResourceManager.GetString("SnowmansNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soulshard Necromantle.
        /// </summary>
        internal static string SoulshardNecromantle {
            get {
                return ResourceManager.GetString("SoulshardNecromantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soulshard Raiment.
        /// </summary>
        internal static string SoulshardRaiment {
            get {
                return ResourceManager.GetString("SoulshardRaiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spartan&apos;s Wargear.
        /// </summary>
        internal static string SpartansWargear {
            get {
                return ResourceManager.GetString("SpartansWargear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectral Captain&apos;s Uniform.
        /// </summary>
        internal static string SpectralCaptainsUniform {
            get {
                return ResourceManager.GetString("SpectralCaptainsUniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirit Fusion Boost Armor.
        /// </summary>
        internal static string SpiritFusionBoostArmor {
            get {
                return ResourceManager.GetString("SpiritFusionBoostArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starsong Shroud.
        /// </summary>
        internal static string StarsongShroud {
            get {
                return ResourceManager.GetString("StarsongShroud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steampowered Exoskeleton.
        /// </summary>
        internal static string SteampoweredExoskeleton {
            get {
                return ResourceManager.GetString("SteampoweredExoskeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Wizard&apos;s Robes.
        /// </summary>
        internal static string SteamWizardsRobes {
            get {
                return ResourceManager.GetString("SteamWizardsRobes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stormrage Armor.
        /// </summary>
        internal static string StormrageArmor {
            get {
                return ResourceManager.GetString("StormrageArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storm Sorcerer.
        /// </summary>
        internal static string StormSorcerer {
            get {
                return ResourceManager.GetString("StormSorcerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swamp Demon&apos;s Nemesis.
        /// </summary>
        internal static string SwampDemonsNemesis {
            get {
                return ResourceManager.GetString("SwampDemonsNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swamp Shaman Robes.
        /// </summary>
        internal static string SwampShamanRobes {
            get {
                return ResourceManager.GetString("SwampShamanRobes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swampstone Platemail.
        /// </summary>
        internal static string SwampstonePlatemail {
            get {
                return ResourceManager.GetString("SwampstonePlatemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tectonic Mantle.
        /// </summary>
        internal static string TectonicMantle {
            get {
                return ResourceManager.GetString("TectonicMantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempered Battlegear.
        /// </summary>
        internal static string TemperedBattlegear {
            get {
                return ResourceManager.GetString("TemperedBattlegear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten-Ton&apos;s Nemesis Robes.
        /// </summary>
        internal static string TenTonsNemesisRobes {
            get {
                return ResourceManager.GetString("TenTonsNemesisRobes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torchflame Mantle.
        /// </summary>
        internal static string TorchflameMantle {
            get {
                return ResourceManager.GetString("TorchflameMantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tortoiseshell Aegis.
        /// </summary>
        internal static string TortoiseshellAegis {
            get {
                return ResourceManager.GetString("TortoiseshellAegis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tortoise&apos;s Nemesis Armor.
        /// </summary>
        internal static string TortoisesNemesisArmor {
            get {
                return ResourceManager.GetString("TortoisesNemesisArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trollforge Platemail.
        /// </summary>
        internal static string TrollforgePlatemail {
            get {
                return ResourceManager.GetString("TrollforgePlatemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troll King&apos;s Nemesis.
        /// </summary>
        internal static string TrollKingsNemesis {
            get {
                return ResourceManager.GetString("TrollKingsNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craftable.
        /// </summary>
        internal static string TypeCraftable {
            get {
                return ResourceManager.GetString("TypeCraftable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-craftable.
        /// </summary>
        internal static string TypeNonCraftable {
            get {
                return ResourceManager.GetString("TypeNonCraftable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wing Warrior&apos;s Armor.
        /// </summary>
        internal static string UncommonAirArmor {
            get {
                return ResourceManager.GetString("UncommonAirArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stonescale Plate Mail.
        /// </summary>
        internal static string UncommonEarthArmor {
            get {
                return ResourceManager.GetString("UncommonEarthArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragonflame Armor.
        /// </summary>
        internal static string UncommonFireArmor {
            get {
                return ResourceManager.GetString("UncommonFireArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystic Armor.
        /// </summary>
        internal static string UncommonSpiritArmor {
            get {
                return ResourceManager.GetString("UncommonSpiritArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seafoam Armor.
        /// </summary>
        internal static string UncommonWaterArmor {
            get {
                return ResourceManager.GetString("UncommonWaterArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinewood Carapace.
        /// </summary>
        internal static string VinewoodCarapace {
            get {
                return ResourceManager.GetString("VinewoodCarapace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volcanic Mantle.
        /// </summary>
        internal static string VolcanicMantle {
            get {
                return ResourceManager.GetString("VolcanicMantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanderer&apos;s Nemesis.
        /// </summary>
        internal static string WanderersNemesis {
            get {
                return ResourceManager.GetString("WanderersNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanderer&apos;s Shroud.
        /// </summary>
        internal static string WanderersShroud {
            get {
                return ResourceManager.GetString("WanderersShroud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior&apos;s Nemesis.
        /// </summary>
        internal static string WarriorsNemesis {
            get {
                return ResourceManager.GetString("WarriorsNemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Fusion Boost Armor.
        /// </summary>
        internal static string WaterFusionBoostArmor {
            get {
                return ResourceManager.GetString("WaterFusionBoostArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Charmer&apos;s Mantle.
        /// </summary>
        internal static string WaveCharmersMantle {
            get {
                return ResourceManager.GetString("WaveCharmersMantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wicked Wraith.
        /// </summary>
        internal static string WickedWraith {
            get {
                return ResourceManager.GetString("WickedWraith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wicker Mantle.
        /// </summary>
        internal static string WickerMantle {
            get {
                return ResourceManager.GetString("WickerMantle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Monarch&apos;s Robes.
        /// </summary>
        internal static string WindMonarchsRobes {
            get {
                return ResourceManager.GetString("WindMonarchsRobes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wing-Wurm&apos;s Nemesis Armor.
        /// </summary>
        internal static string WingWurmsNemesisArmor {
            get {
                return ResourceManager.GetString("WingWurmsNemesisArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witch&apos;s Robes.
        /// </summary>
        internal static string WitchsRobes {
            get {
                return ResourceManager.GetString("WitchsRobes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyvern&apos;s Nemesis.
        /// </summary>
        internal static string WyvernsNemesis {
            get {
                return ResourceManager.GetString("WyvernsNemesis", resourceCulture);
            }
        }
    }
}
